# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'designer/Settings.ui'
#
# Created by: PyQt5 UI code generator 5.14.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_settingsDialog(object):
    def setupUi(self, settingsDialog):
        settingsDialog.setObjectName("settingsDialog")
        settingsDialog.setWindowModality(QtCore.Qt.WindowModal)
        settingsDialog.resize(363, 300)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(settingsDialog.sizePolicy().hasHeightForWidth())
        settingsDialog.setSizePolicy(sizePolicy)
        settingsDialog.setMinimumSize(QtCore.QSize(0, 0))
        self.gridLayout = QtWidgets.QGridLayout(settingsDialog)
        self.gridLayout.setObjectName("gridLayout")
        self.pages = QtWidgets.QTabWidget(settingsDialog)
        self.pages.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.pages.setObjectName("pages")
        self.loginSettings = QtWidgets.QWidget()
        self.loginSettings.setObjectName("loginSettings")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.loginSettings)
        self.verticalLayout.setObjectName("verticalLayout")
        self.credentialGroup = QtWidgets.QGroupBox(self.loginSettings)
        self.credentialGroup.setObjectName("credentialGroup")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.credentialGroup)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.storecredsDesc = QtWidgets.QLabel(self.credentialGroup)
        self.storecredsDesc.setWordWrap(True)
        self.storecredsDesc.setObjectName("storecredsDesc")
        self.gridLayout_2.addWidget(self.storecredsDesc, 1, 0, 1, 3)
        self.storecredsLabel = QtWidgets.QLabel(self.credentialGroup)
        self.storecredsLabel.setObjectName("storecredsLabel")
        self.gridLayout_2.addWidget(self.storecredsLabel, 0, 0, 1, 1)
        self.storecredsCheckbox = QtWidgets.QCheckBox(self.credentialGroup)
        self.storecredsCheckbox.setText("")
        self.storecredsCheckbox.setObjectName("storecredsCheckbox")
        self.gridLayout_2.addWidget(self.storecredsCheckbox, 0, 2, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 0, 1, 1, 1)
        self.verticalLayout.addWidget(self.credentialGroup)
        self.loginGroup = QtWidgets.QGroupBox(self.loginSettings)
        self.loginGroup.setObjectName("loginGroup")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.loginGroup)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.autologinLabel = QtWidgets.QLabel(self.loginGroup)
        self.autologinLabel.setObjectName("autologinLabel")
        self.gridLayout_3.addWidget(self.autologinLabel, 0, 0, 1, 1)
        self.autologinCheckbox = QtWidgets.QCheckBox(self.loginGroup)
        self.autologinCheckbox.setText("")
        self.autologinCheckbox.setObjectName("autologinCheckbox")
        self.gridLayout_3.addWidget(self.autologinCheckbox, 0, 2, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem1, 0, 1, 1, 1)
        self.autologinDesc = QtWidgets.QLabel(self.loginGroup)
        self.autologinDesc.setWordWrap(True)
        self.autologinDesc.setObjectName("autologinDesc")
        self.gridLayout_3.addWidget(self.autologinDesc, 1, 0, 1, 3)
        self.verticalLayout.addWidget(self.loginGroup)
        self.pages.addTab(self.loginSettings, "")
        self.usabilitySettings = QtWidgets.QWidget()
        self.usabilitySettings.setObjectName("usabilitySettings")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.usabilitySettings)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.storageGroup = QtWidgets.QGroupBox(self.usabilitySettings)
        self.storageGroup.setObjectName("storageGroup")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.storageGroup)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.saveondownloadLabel = QtWidgets.QLabel(self.storageGroup)
        self.saveondownloadLabel.setObjectName("saveondownloadLabel")
        self.gridLayout_4.addWidget(self.saveondownloadLabel, 0, 0, 1, 1)
        self.autouploadLabel = QtWidgets.QLabel(self.storageGroup)
        self.autouploadLabel.setObjectName("autouploadLabel")
        self.gridLayout_4.addWidget(self.autouploadLabel, 3, 0, 1, 1)
        self.saveondownloadCheckbox = QtWidgets.QCheckBox(self.storageGroup)
        self.saveondownloadCheckbox.setText("")
        self.saveondownloadCheckbox.setObjectName("saveondownloadCheckbox")
        self.gridLayout_4.addWidget(self.saveondownloadCheckbox, 0, 2, 1, 1)
        self.autouploadCheckbox = QtWidgets.QCheckBox(self.storageGroup)
        self.autouploadCheckbox.setText("")
        self.autouploadCheckbox.setObjectName("autouploadCheckbox")
        self.gridLayout_4.addWidget(self.autouploadCheckbox, 3, 2, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem2, 0, 1, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem3, 3, 1, 1, 1)
        self.saveondownloadDesc = QtWidgets.QLabel(self.storageGroup)
        self.saveondownloadDesc.setWordWrap(True)
        self.saveondownloadDesc.setObjectName("saveondownloadDesc")
        self.gridLayout_4.addWidget(self.saveondownloadDesc, 1, 0, 1, 3)
        self.autouploadDesc = QtWidgets.QLabel(self.storageGroup)
        self.autouploadDesc.setWordWrap(True)
        self.autouploadDesc.setObjectName("autouploadDesc")
        self.gridLayout_4.addWidget(self.autouploadDesc, 4, 0, 1, 3)
        self.line = QtWidgets.QFrame(self.storageGroup)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_4.addWidget(self.line, 2, 0, 1, 3)
        self.verticalLayout_2.addWidget(self.storageGroup)
        self.savelocationGroup = QtWidgets.QGroupBox(self.usabilitySettings)
        self.savelocationGroup.setObjectName("savelocationGroup")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.savelocationGroup)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.savelocationLabel = QtWidgets.QLabel(self.savelocationGroup)
        self.savelocationLabel.setObjectName("savelocationLabel")
        self.gridLayout_5.addWidget(self.savelocationLabel, 0, 0, 1, 1)
        self.saveLocationPath = QtWidgets.QLineEdit(self.savelocationGroup)
        self.saveLocationPath.setText("")
        self.saveLocationPath.setReadOnly(True)
        self.saveLocationPath.setObjectName("saveLocationPath")
        self.gridLayout_5.addWidget(self.saveLocationPath, 0, 1, 1, 1)
        self.changeSaveLocationButton = QtWidgets.QToolButton(self.savelocationGroup)
        self.changeSaveLocationButton.setObjectName("changeSaveLocationButton")
        self.gridLayout_5.addWidget(self.changeSaveLocationButton, 0, 2, 1, 1)
        self.saveLocationDesc = QtWidgets.QLabel(self.savelocationGroup)
        self.saveLocationDesc.setScaledContents(False)
        self.saveLocationDesc.setWordWrap(True)
        self.saveLocationDesc.setObjectName("saveLocationDesc")
        self.gridLayout_5.addWidget(self.saveLocationDesc, 1, 0, 1, 3)
        self.verticalLayout_2.addWidget(self.savelocationGroup)
        self.pages.addTab(self.usabilitySettings, "")
        self.gridLayout.addWidget(self.pages, 0, 0, 1, 1)

        self.retranslateUi(settingsDialog)
        self.pages.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(settingsDialog)

    def retranslateUi(self, settingsDialog):
        _translate = QtCore.QCoreApplication.translate
        settingsDialog.setWindowTitle(_translate("settingsDialog", "Settings"))
        self.credentialGroup.setTitle(_translate("settingsDialog", "Credential Storage"))
        self.storecredsDesc.setText(_translate("settingsDialog", "This feature will store your credentials on your next sign-in in a json document located at \"VirtualTabletop/credentials.json\". This feature should only be used on a secure computer you own as it stores your info in plaintext, which could open your credentials to theft."))
        self.storecredsLabel.setText(_translate("settingsDialog", "Store Credentials:"))
        self.loginGroup.setTitle(_translate("settingsDialog", "Login"))
        self.autologinLabel.setText(_translate("settingsDialog", "Auto Log-In:"))
        self.autologinDesc.setText(_translate("settingsDialog", "This feature will automatically prompt you to log-in whenever you start this app. This will be overridden if there is no currently linked Firebase. If you have stored credentials, this feature will automatically log you in. If this feature is enabled and you link a Firebase, you will be automatically prompted to log-in."))
        self.pages.setTabText(self.pages.indexOf(self.loginSettings), _translate("settingsDialog", "Login Settings"))
        self.storageGroup.setTitle(_translate("settingsDialog", "Storage"))
        self.saveondownloadLabel.setText(_translate("settingsDialog", "Save on Download:"))
        self.autouploadLabel.setText(_translate("settingsDialog", "Auto-Upload:"))
        self.saveondownloadDesc.setText(_translate("settingsDialog", "When enabled, this feature will automatically save any game you open from Firebase so that you will have a local copy."))
        self.autouploadDesc.setText(_translate("settingsDialog", "When enabled, this feature will automatically upload any game or game collection you make to Firebase if you have one linked."))
        self.savelocationGroup.setTitle(_translate("settingsDialog", "Save Location"))
        self.savelocationLabel.setText(_translate("settingsDialog", "Save Location: "))
        self.saveLocationPath.setPlaceholderText(_translate("settingsDialog", "./localboards"))
        self.changeSaveLocationButton.setText(_translate("settingsDialog", "..."))
        self.saveLocationDesc.setText(_translate("settingsDialog", "This is the location where all local games and game collections will be stored. The default save location is \"VirtualTabletop/localboards\". Changing this location will not copy over any games or game collections from the previous location."))
        self.pages.setTabText(self.pages.indexOf(self.usabilitySettings), _translate("settingsDialog", "Usability Settings"))
